Repository acm-ucr/hsp-website, pull requests merged in 2024-01, with the labels that each got.

#18 About Us Page
  src/app/about/page.js
  src/components/about/Us.js
Labels: good first issue

#14 donate button
  src/app/donate/page.js
  src/components/donate/Donate.js
Labels: ready for review

#16 created footer
  src/components/Footer.js
Labels: do not merge

#13 Create Mission Section
  src/app/about/page.js
  src/components/about/Mission.js
  src/data/Mission.js
Labels: ready for review

#15 Lead Title
  src/app/board/page.js
  src/components/board/LeadTitle.js
Labels: enhancement, do not merge

#19 Profile Card
  src/app/board/page.js
  src/app/page.js
  src/components/board/Profile.js
  src/components/board/Team.js
  src/public/Joel.png
  src/public/assets/board/Alan.svg
  src/public/assets/board/George.svg
  src/public/assets/board/Javen.svg
  src/public/assets/board/Joel.svg
  src/public/assets/board/Jordy.svg
  src/public/assets/board/Khulan.svg
  src/public/assets/board/Lawrence.svg
  src/public/assets/board/Marlon.svg
  src/public/assets/board/Mehmet.svg
  src/public/assets/board/Theopolis.svg
  src/public/assets/board/Uma.svg
Labels: ready for review

#29 created propulsion page
  src/app/projects/page.js
  src/components/projects/poseidon/Propulsion.js
Labels: ready for review

#17 Created contact page
  src/app/donate/page.js
  src/components/donate/Contact.js
Labels: enhancement, ready for review
