Repository acm-ucr/hsp-website, pull requests merged in 2024-03, with the labels that each got.

#55 created Sponsors section
  src/app/donate/page.js
  src/components/donate/Sponsors.js
  src/data/Sponsors.js
Labels: ready for review

#76 carousel
  src/app/join/page.js
  src/components/projects/poseidon/carousel.jsx
  src/data/Poseidon/carousel.js
  src/public/assets/join/chung.svg
  src/public/assets/join/rocket.svg
  src/public/assets/join/team.svg
  src/public/assets/join/working.svg
  tailwind.config.js
Labels: ready for review

#82 Mission Responsiveness
  src/app/about/page.js
  src/app/page.js
  src/components/about/Mission.js
Labels: ready for review

#56 Kelly/project descriptions
  src/app/projects/page.js
  src/components/projects/poseidon/Description.js
Labels: do not merge

#54 LeadsTitle.js changed into Header.js
  src/app/board/page.js
  src/app/events/page.js
  src/components/board/Header.js
  src/components/board/Team.js
Labels: ready for review

#86 Hannah/landing page redo
  src/components/Footer.js
  src/components/about/Landing.js
  src/components/donate/Contact.js
Labels: ready for review

#50 fixed donate button
  src/components/donate/Contact.js
  src/components/donate/Donate.js
  src/components/donate/Sponsors.js
Labels: ready for review

#52 created see more button
  src/components/about/Button.js
  src/components/about/UpcomingSection.js
Labels: ready for review

#79 Join now button hover changes
  src/components/Button.js
Labels: ready for review

#93 added linked in / email data, changed Herrera's title
  src/components/board/Profile.js
  src/data/Board.js
Labels: ready for review

#85 update nav bar to show active tab
  src/components/Navigation.js
Labels: ready for review

#83 timeline response
  src/app/projects/page.js
  src/components/projects/poseidon/Timeline.js
Labels: ready for review

#84 responsiveness abt us
  src/components/about/Us.js
Labels: do not merge

#80 Kelly/project description responsiveness
  package-lock.json
  src/app/projects/page.js
  src/components/projects/poseidon/Description.js
  src/components/projects/poseidon/Timeline.js
Labels: do not merge

#81 Added sponsors description responsiveness
  src/app/donate/page.js
  src/components/PageTitle.js
  src/components/donate/Contact.js
  src/components/donate/Descriptions.js
  src/components/donate/Donate.js
  src/components/donate/Sponsors.js
  src/components/donate/Table.js
  src/components/projects/poseidon/Description.js
Labels: question

#99 404 page
  src/app/not-found.js
  src/public/assets/not-found/bear.svg
Labels: ready for review
